### ISSUE TITLE
Unable to run locally

### ISSUE THREAD

**Issue by kyyberi** [apinf/apiops-meetup#37]
Cloned repo to local

started "meteor" from root

W20160109-11:40:27.958(2)? (STDERR) TypeError: Cannot read property 'meetup' of undefined
W20160109-11:40:27.958(2)? (STDERR)     at server/methods.js:3:1
W20160109-11:40:27.958(2)? (STDERR)     at server/methods.js:163:1
W20160109-11:40:27.958(2)? (STDERR)     at /home/kyyberi/Github/apiops-meetup-website/.meteor/local/build/programs/server/boot.js:242:10
W20160109-11:40:27.959(2)? (STDERR)     at Array.forEach (native)
W20160109-11:40:27.962(2)? (STDERR)     at Function._.each._.forEach (/home/kyyberi/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20160109-11:40:27.962(2)? (STDERR)     at /home/kyyberi/Github/apiops-meetup-website/.meteor/local/build/programs/server/boot.js:137:5
I20160109-11:40:31.454(2)? setting timer for:  Sat Jan 09 2016 12:30:00 GMT+0200 (EET)
I20160109-11:40:31.455(2)? setting timer for:  Sat Jan 09 2016 12:30:00 GMT+0200 (EET)
W20160109-11:40:31.472(2)? (STDERR) 
W20160109-11:40:31.472(2)? (STDERR) /home/kyyberi/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20160109-11:40:31.472(2)? (STDERR)                         throw(ex);
W20160109-11:40:31.472(2)? (STDERR)                               ^
W20160109-11:40:31.476(2)? (STDERR) TypeError: Cannot read property 'meetup' of undefined
W20160109-11:40:31.476(2)? (STDERR)     at server/methods.js:3:1
W20160109-11:40:31.476(2)? (STDERR)     at server/methods.js:163:1
W20160109-11:40:31.476(2)? (STDERR)     at /home/kyyberi/Github/apiops-meetup-website/.meteor/local/build/programs/server/boot.js:242:10
W20160109-11:40:31.476(2)? (STDERR)     at Array.forEach (native)
W20160109-11:40:31.476(2)? (STDERR)     at Function._.each._.forEach (/home/kyyberi/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20160109-11:40:31.477(2)? (STDERR)     at /home/kyyberi/Github/apiops-meetup-website/.meteor/local/build/programs/server/boot.js:137:5
=> Exited with code: 8
=> Your application is crashing. Waiting for file change.

**Comment by 55** [comment]
In order to start it locally you need:
1. Install Meteor.js
2. Clone https://github.com/APIOps/apiops-meetup-website
3. Create settings.json
4. Type **meteor --settings /path/to/settings.json** in the project directory

I will add instructions how to start project locally to README file.
